### ISSUE TITLE
Terrain generation

### ISSUE THREAD

**Issue by Silent-Hunter** [jgosar/mine-city-2000#10]
I think it would be cool if instead of having an obsidian wall surrounding the converted city, it just had regular Minecraft terrain generation so the city appears in an otherwise normal Minecraft world. What do you think?

**Comment by jgosar** [comment]
In that case it would also make sense for the Minecraft terrain to continue from the city edges at the same altitude, otherwise there would still be a sharp drop/high wall at the edge of the city. And I don't think it's possible to convince Minecraft's terrain generation logic to do that. It just generates terrain randomly.

I guess it could be possible to place the city into an existing MC world and then modifying its already existing terrain to match the terrain heights of the city. And it would also be possible to replace the current sharp-edged SimCity-style hills with softer Minecraft-style ones and cover them with grass, so the city would fit in better.

But this would take a huge amount of time, so I don't think it's realistic for me to promise that this will ever get done.

Thanks for the suggestion though, this really would be cool 👍

**Comment by Silent-Hunter** [comment]
I edited one of the generated worlds a while back to change the world generation settings away from flat, and I'm pretty sure it actually contoured to the edges of the city. I'll try that again tomorrow and see what happens.

**Comment by jgosar** [comment]
Hmm ok, let me know how that works out. Changing the terrain generation settings and removing the obsidian wall should be relatively easy for me to do, the only question is if Minecraft will actually match the terrain height.

**Comment by jgosar** [comment]
I just tried it and this is the result: 
![image](https://user-images.githubusercontent.com/36840705/213397383-7efc139d-46a1-4a18-b210-7c6122004bb5.png)

It's not really ideal, but I could add it as an option

**Comment by jgosar** [comment]
And also I'm not sure what's up with the mud on the roads there ^^ :)

**Comment by Silent-Hunter** [comment]
That's a very odd result! What I did was I converted the world, and then just edited the nbt data before letting Minecraft load it. So there wasn't anything generated under the city. I'm not sure if your program can emulate that behavior or not.

**Comment by jgosar** [comment]
There is nothing under the city in my screenshot above either. The terrain is being generated from the edge of the city onward.

**Comment by Silent-Hunter** [comment]
Oh I see! I must be mistaken then. It would still be a cool option to have it do this, then I can build bridges, etc. between the city and the terrain and use it on my server. :)

**Comment by jgosar** [comment]
@Silent-Hunter I finally found the time to implement this small change, now you can select the "Generate terrain around the city" option to generate random Minecraft terrain around the city instead of having  an obsidian wall

**Comment by Silent-Hunter** [comment]
Wow thanks!
